AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Setting up IAM user for Packer. That will be used to spin up EC2 instance and EBS volume.

Resources:

  PackerUser:
    Type: AWS::IAM::User
    Properties:
      UserName: "packer-user"

  PackerUserAccessKey:
    Type: AWS::IAM::AccessKey
    DependsOn:
      - PackerUser
    Properties:
      Serial: 0
      Status: Active
      UserName: !Ref "PackerUser"

  PackerUserPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - PackerUserAccessKey
    Properties:
      Users:
        - !Ref "PackerUser"
      PolicyName: "packer-user-policy"
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - iam:PassRole
              - ec2:AttachVolume
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:CopyImage
              - ec2:CreateImage
              - ec2:CreateKeypair
              - ec2:CreateSecurityGroup
              - ec2:CreateSnapshot
              - ec2:CreateTags
              - ec2:CreateVolume
              - ec2:DeleteKeypair
              - ec2:DeleteSecurityGroup
              - ec2:DeleteSnapshot
              - ec2:DeleteVolume
              - ec2:DeregisterImage
              - ec2:DescribeImageAttribute
              - ec2:DescribeImages
              - ec2:DescribeInstances
              - ec2:DescribeRegions
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSnapsots
              - ec2:DescribeSubnets
              - ec2:DescribeTags
              - ec2:DescribeVolumes
              - ec2:DetachVolume
              - ec2:GetPasswordData
              - ec2:ModifyImageAttribute
              - ec2:ModifyInstanceAttribute
              - ec2:ModifySnapshotAttribute
              - ec2:RegisterImage
              - ec2:RunInstances
              - ec2:StopInstances
              - ec2:TerminateInstances
            Resource: "*"

Outputs:

  PackerUserAccessKeySecret:
    Description: >
      Secret access key for Packer user.
    Value: !GetAtt "PackerUserAccessKey.SecretAccessKey"

  PackerUserAccessKey:
    Description: >
      Access key for Packer user.
    Value: !Ref "PackerUserAccessKey"